# ---- Server
server.port=8080

# ---- Cache
spring.cache.type=caffeine

# ---- Actuator (exponer endpoints básicos)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized

# ---- DiceBear (props usadas por DiceBearProps)
dicebear.base-url=https://api.dicebear.com
dicebear.version=8.x

# ---- Resilience4j
# Retry
resilience4j.retry.instances.dicebear.max-attempts=3
resilience4j.retry.instances.dicebear.wait-duration=300ms

# TimeLimiter
resilience4j.timelimiter.instances.dicebear.timeout-duration=2s

# CircuitBreaker
resilience4j.circuitbreaker.instances.dicebear.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.dicebear.sliding-window-size=20
resilience4j.circuitbreaker.instances.dicebear.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.dicebear.wait-duration-in-open-state=30s
