server.port=8080

dicebear.base-url=https://api.dicebear.com
dicebear.version=7.x
dicebear.connect-timeout-millis=2000
dicebear.response-timeout-millis=3000

spring.cache.type=caffeine
spring.cache.cache-names=avatars
spring.cache.caffeine.spec=maximumSize=5000,expireAfterWrite=7d

management.endpoints.web.exposure.include=health,info,metrics
management.info.build.enabled=true
management.endpoint.health.show-details=never

springdoc.swagger-ui.path=/swagger-ui

resilience4j.retry.instances.dicebear.max-attempts=3
resilience4j.retry.instances.dicebear.wait-duration=300ms
